@api = http://localhost:5000/products
GET {{api}}
Content-Type: application/json

{
 "db":"appstore",
 "table":"Products"
}
###
POST {{api}}
Content-Type: application/json

{
  "db":"webstore",
  "table":"Products",
  "data":{
  "name":"Play station 1",
  "description":"consola de videojuegos",
  "quantity":20
  }
}

### ExecSQL

GET {{api}}/sql
Content-Type: application/json

{
 "sql":"SELECT * FROM [webstore].[dbo].[products] WHERE id =3 and quantity=10"
}
